#! /bin/bash

##                                 md5cd
## -----------------------------------------------------------------------------
## generate and check MD5 hash recursively between two directories
## David R. Hill
## -----------------------------------------------------------------------------
## HOW TO USE THIS SCRIPT
## This script performs a series of actions:
## 1 - Generate and verify MD5 hashes recursively in two unique user specified
##     directories (results in 'md5sum_check_DIR#.txt')
## 2 - Compare list of MD5 hashes in DIR1 to list of MD5 hashes in DIR2
## 3 - Output lists of files that are present in DIR1 but not present in DIR2
## 4 - Output list of files in DIR1 that are identical in DIR2 

## Setup variables
## set number of cores for multicore MD5 generation
MAXCORES=$(grep -c ^processor /proc/cpuinfo)
## start time
DT1=$(date '+%d/%m/%Y %H:%M:%S')

## set equivalent variables for arguments passed from command line
DIR1=$1
DIR2=$2
CORES=$3


## if arguments are not supplied, prompt user for directories and cores
if [ -z "$1" ]
then
    read -e -p "Source directory (where are you copying from?):" DIR1
fi

if [ -z "$2" ]
then
read -e -p "Target directory (where are you copying to?):" DIR2
fi

if [ -z "$3" ]
then
read -p "How many cores (max is "$MAXCORES")?:" CORES
fi

## confirm setup interactively prior to running md5sum
while true; do
    read -p "Compare MD5 checksums in "$DIR1" to "$DIR2" using "$CORES" core(s) [y/n]?" yn
    case $yn in
        [Yy]* )
	    ## find largest file to compute block size
	    BSIZE=$(find $DIR1 -type f -printf "%s\t%p\n" | sort -n | tail -1 | awk '{print $1}')
	    ## generate md5sum recursively
	    find $DIR1 -type f | parallel -j $CORES --block $BSIZE md5sum > md5sum_DIR1.txt 
	    ## verify md5sums against files
	    cat md5sum_DIR2.txt | parallel --pipe -j $CORES md5sum -c > md5sum_check_DIR1_.txt 
	    cut -f 1 -d\  md5sum_DIR1.txt > list1.log

	    ## find largest file to compute block size
	    BSIZE=$(find $DIR2 -type f -printf "%s\t%p\n" | sort -n | tail -1 | awk '{print $1}')
	    ## generate md5sum recursively
	    find $DIR2 -type f | parallel -j $CORES --block $BSIZE md5sum > md5sum_DIR2.txt 
	    ## verify md5sums against files
	    cat md5sum_DIR2.txt | parallel --pipe -j $CORES md5sum -c > md5sum_check_DIR2_.txt 
	    cut -f 1 -d\  md5sum_DIR2.txt > list2.log

	    ## set locale to C for faster string matching in grep
	    export LC_ALL=C

	    ## compare two md5sum reports and output list of differences
	    ## and list of similarities
	    ## this is a list of files that are different between the two directories
	    ## create data file and add header line
	    echo '## These files from '$DIR1' are NOT present in '$DIR2 > md5cd_results.log
	    echo 'Checksum path' >> md5cd_results.log
	    cat md5sum_DIR1.txt | parallel -j $CORES --pipe grep '-v -f list2.log' {} >> md5cd_results.log
	    echo '--------------------------------------------------------------------------------' >> md5cd_results.log
	    
	    ## this is a list of files that are the same in both directories
	    echo '## These files are IDENTICAL in both '$DIR1' and '$DIR2 >> md5cd_results.log
	    echo 'Checksum path' >> md5cd_results.log
	    cat md5sum_DIR1.txt | parallel -j $CORES --pipe grep '-f list2.log' {} >> md5cd_results.log
	    echo '--------------------------------------------------------------------------------' >> md5cd_results.log
	    echo "md5cd initiated at "$DT1" and completed at "$(date '+%d/%m/%Y %H:%M:%S') >> md5cd_results.log
		    
	    ## remove extraneous log files
	    rm list1.log list2.log
	    
	    break;;
	
        [Nn]* ) exit;;
        * ) echo "Please answer y or n.";;
    esac
done

# MIT License

# Copyright (c) 2018 David R. Hill

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


